# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import golden_fish_pb2 as golden__fish__pb2


class GoldenFishStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterValve = channel.unary_unary(
                '/goldenfish.GoldenFish/RegisterValve',
                request_serializer=golden__fish__pb2.Valve.SerializeToString,
                response_deserializer=golden__fish__pb2.Status.FromString,
                )


class GoldenFishServicer(object):
    """Interface exported by the server.
    """

    def RegisterValve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoldenFishServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterValve': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterValve,
                    request_deserializer=golden__fish__pb2.Valve.FromString,
                    response_serializer=golden__fish__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'goldenfish.GoldenFish', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GoldenFish(object):
    """Interface exported by the server.
    """

    @staticmethod
    def RegisterValve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/goldenfish.GoldenFish/RegisterValve',
            golden__fish__pb2.Valve.SerializeToString,
            golden__fish__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
