# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: golden_fish.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='golden_fish.proto',
  package='goldenfish',
  syntax='proto3',
  serialized_options=b'\n\027com.lablabla.goldenfishB\017GoldenFishProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11golden_fish.proto\x12\ngoldenfish\"(\n\x05Valve\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2D\n\nGoldenFish\x12\x36\n\rRegisterValve\x12\x11.goldenfish.Valve\x1a\x12.goldenfish.StatusB,\n\x17\x63om.lablabla.goldenfishB\x0fGoldenFishProtoP\x01\x62\x06proto3'
)




_VALVE = _descriptor.Descriptor(
  name='Valve',
  full_name='goldenfish.Valve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='goldenfish.Valve.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='goldenfish.Valve.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=73,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='goldenfish.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='goldenfish.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='goldenfish.Status.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['Valve'] = _VALVE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Valve = _reflection.GeneratedProtocolMessageType('Valve', (_message.Message,), {
  'DESCRIPTOR' : _VALVE,
  '__module__' : 'golden_fish_pb2'
  # @@protoc_insertion_point(class_scope:goldenfish.Valve)
  })
_sym_db.RegisterMessage(Valve)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'golden_fish_pb2'
  # @@protoc_insertion_point(class_scope:goldenfish.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_GOLDENFISH = _descriptor.ServiceDescriptor(
  name='GoldenFish',
  full_name='goldenfish.GoldenFish',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=116,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterValve',
    full_name='goldenfish.GoldenFish.RegisterValve',
    index=0,
    containing_service=None,
    input_type=_VALVE,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOLDENFISH)

DESCRIPTOR.services_by_name['GoldenFish'] = _GOLDENFISH

# @@protoc_insertion_point(module_scope)
